version: '3.7'
services:

  nodejs:
    build: ./gate-simulator
    image: node-app:1.0.0
    container_name: bank-simulator
    ports:
      - '9999:9999'

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass